### ISSUE TITLE
Graph paradigm shift - store it, don't build it

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1043]
Our current implementation rebuilds the graph on demand for every renku command that requires it. Because of the nature of the graph this requires expensive git tree traversals and a lot of file i/o. 

The proposal is to store the graph on disk instead - this way, all the renku commands would query the generated graph instead of re-creating it first. The graph service could also consume this data directly, greatly speeding up the graph building.

**Comment by jsam** [comment]
This ticket is same as  #864, what we are missing is not the general idea but more concrete implementation implications for this. I propose we use one of those 2 tickets as a more general breakdown which is needed to achieve this.

**Comment by Panaetius** [comment]
I think most of the pieces are in place to really start working on the new graph building. We can do this while still keeping `renku log` the same.

The steps as I see them are:
- Store metadata in a single file
- Use that single file for our commands
- Store metadata from all commits in the single file
- Add a command similar to log that queries this file instead of walking commits

we can do this sequence independently for workflows and datasets (not sure if it's needed for Project metadata? might need to create issues for that as well). Then for the last step we can join/concat the implementations to get a new `renku log` (`renku graph dump` ?) that works solely on the 2-3 single files (one for datasets, 1-2 for provenance/workflows).
Once that works well, we can retire `renku log` and remove old metadata files in a further migration.

**Comment by Panaetius** [comment]
Done :tada:
