### ISSUE TITLE
`renku migrate` doesn't make the pointers directory

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1141]
**Describe the bug**
running `renku migrate` fails to make the `.renku/pointers` directory which makes `renku dataset add` fail

**To Reproduce**

1. migrate an old project
2. run `renku dataset create mydataset`
3. run `renku dataset add ...

The `.renku/pointers` directory should either be optional or include a `.gitkeep` file so that it doesn't get removed if the user does `git clean -dff`.

**Comment by mohammad-sdsc** [comment]
This is not normally possible to have this case: The external storage PR was merged after the new migration and technically one cannot have an external file which gets affected by the migration. Moreover, the `.renku/pointer` directory gets created every time.

I could not re-produce this. Can you please give me the link to your project.

Also note that if you've created a project to play with the external storage draft PR, then you should re-create it (or undo changes) because the implementation in the final PR has changed.

**Comment by mohammad-sdsc** [comment]
This is happening due to https://github.com/SwissDataScienceCenter/renku-python/issues/1143.
