### ISSUE TITLE
feat: add integration for cloud object stores

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1223]
It would be nice to add support for importing data from cloud object stores. Quite often, I'm trying to import some data from S3-like bucket to a dataset and this flow is a bit clunky when importing large data (and having a dirty repo) since it requires me to have data copied twice. 

Current flow I'm using is the following (please note I do not copy directly to the repo since it's dirty already usually):

```
mc cp <bucket>/<file> /tmp/somefile
renku dataset add --create mydataset /tmp/somefile
```

I think more convenient flow would be:

```
renku config myteam.s3.config <access_key>
renku dataset add mydataset myteam.s3/bucket/<fileImImporting>
```

This would result in direct import, less data duplication, and clunkiness. Also, it would enable users to export their datasets to buckets (with the metadata!).

**Comment by rokroskar** [comment]
This would be a great feature to have! I think we should also consider what has been done in https://github.com/SwissDataScienceCenter/renku-python/pull/974 i.e. optionally use pointer files instead of copying the data. We would then also need some capability to stream this data on-demand. We have had a few discussions on this in the past - see also https://github.com/swissdatasciencecenter/renku-python/issues/815 and https://github.com/SwissDataScienceCenter/renku/issues/695.

**Comment by Panaetius** [comment]
Will be tracked separately as part of a larger epic
