### ISSUE TITLE
Merge LocalClient into Project

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1349]
`LocalClient` seems to be an unnecessary abstraction which can be merged into a `Project` object. In addition to a cleaner abstraction, this allows us to put all renku project's configuration in `metadata.yml` and remove `renku.ini`. We can also add some metadata about datasets to avoid parsing datasets' metadata files all the time.

**Comment by rokroskar** [comment]
the `metadata.yml` and `renku.ini` play very different roles. `renku.ini` is in a format that is somewhat known to users and is meant to be edited in a text editor or via renku commands (like the git config, for example). `metadata.yml` on the other hand isn't really supposed to be touched by a user and with the changes to the graph storage it's not clear to me that this file will even be around much longer. 

In terms of `LocalClient` vs `Project` I agree - since we don't envisage instantiating projects using a remote client, this would make sense.

**Comment by Panaetius** [comment]
Will be done using CommandBuilder instead of merging with Project
