### ISSUE TITLE
Simplify lineage/workflow metadata

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1554]
Currently we use a mixture of ontologies (`PROV-O`, `wf4ever`, and `renku`) to store lineage and workflows metadata: `prov:Plan` (i.e. `Run` class) to store execution templates, `wfprov:ProcessRun` for executions, `wfprov:WorkflowRun` for a series of execution, etc. Our usage of these ontologies is not consistent in some places (e.g. `wfdesc:Process` should be used as a template for `wfprov:ProcessRun`) which can cause confusion. Moreover, our workflow steps are homogenous (i.e. executions of shell commands) and we do not require sophisticated workflow description as provided by `wf4ever`.

We can simplify our metadata by using only `prov:Plan` and `prov:Activity` and the related constructs and avoid using `wf4ever` totally.

**Acceptance Criteria**
* All references to `wfprov` constructs are removed.
* `wfprov:ProcessRun` is replaced with `prov:Activity`
* `wfprov:WorkflowRun` is replaced with `prov:Collection` and its (redundant) Usages and Generations are removed.

**Comment by rokroskar** [comment]
Thanks @mohammad-sdsc I think this is definitely going in the right direction. If I understand correctly, in this proposal a workflow would be a collection of activities? I think the general idea is OK but it might be too generic. I think one of the issues we have is verbosity in the KG, but another is trying to force very abstract concepts to satisfy very specific semantic needs (e.g. a directory is also a `prov:Collection` of files). These abstract classes from e.g. `prov` are meant to be extended in order to serve a specific purpose - so maybe it's safe at this point to create our own extensions in the renku ontology if we haven't found ones that satisfy our needs elsewhere?

**Comment by mohammad-sdsc** [comment]
I believe the semantics for a `WorkflowRun` needs to be discussed in more details since it's something coming from `wf4ever` and we use it in an abstract way. We have a DAG of `Process` templates and when we do a rerun/update we execute some of those templates (a path in the DAG) and we create a `ProcessRun` for each template; the set of these ProcessRuns is stored in a `WorkflowRun` and we don't have a corresponding concept in the DAG (e.g. a Workflow consisting of a set of Processes). Having that in mind, I totally agree with you that we should not over-simplify things when necessary (as well as we should over-complicate things unnecessarily). We need a discussions on this matter to define necessary semantics.

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
