### ISSUE TITLE
Add --revision to new workflow log

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1732]
change `renku graph log` to `renku graph workflow dump` and add a `--revision` flag and `<paths>` argument to output triples for a certain revision and/or paths.

Only support `--revision` for commits done after new graph building, with a message to users for earlier commits to checkout the commit themselves, run migrations, `renku graph generate` and then generate the log.

**Comment by rokroskar** [comment]
Is `renku graph workflow dump --revision <revision>` supposed to take other arguments? Or is the idea to dump the entire provenance graph at that revision? Otherwise I could imagine e.g. `renku graph workflow dump --revision <revision> <path>` or `renku graph workflow dump --revision <revision> <name>` for named workflows.

**Comment by Panaetius** [comment]
it should have the same arguments as `renku log`.

**Comment by mohammad-sdsc** [comment]
### Implementation Considerations
Renku updates workflow provenance metadata when executing `run`, `rerun`, or `update` commands and updates dataset metadata when running `dataset` command. These metadata are read for some of these commands (e.g. when updating, Renku needs to know what workflow created a file) as well as commands that show workflow to users like `log` or `export`. There are some implementations trade-offs on how we store graph metadata in a Renku project:
1. Storage format: JSON-LD or some custom intermediate format
2. Storage structure: Store all metadata in a single file or split the metadata across multiple files

## Storage Format

||Pros|Cons|
|-|-|-|
| **JSON-LD**|<ul><li>Data can be loaded directly in tools that support JSON-LD (e.g. rdflib) without loading Renku models first.<br>**Note:** For this to work, metadata must be already at the latest version without requiring any migration.|<ul><li>Larger metadata size.|
|**Custom**|<ul><li>Smaller metadata size.<li>Loading custom metadata can be faster compared to loading JSON-LD models.|<ul><li>Metadata must be exported to JSON-LD whenever required.|

## Storage Structure
||Pros|Cons|
|-|-|-|
|**Single-File**|<ul><li>Faster loads<li>Smaller metadata size on disk|<ul><li>The whole graph must be always loaded when updating it<br>**Note:** This can be avoided if metadata is treated as text and we append updates at the end; we must remove (possible) duplicates when loading the metadata.|
|**Split Files**|<ul><li>No need to load the graph for commands that only append to it (e.g. `run`)<li>Easier filtering on git revisions|<ul><li>Longer loading times<li>Larger metadata size due to duplicates|

## Quantitative Analysis
We generated new graph metadata (both single-file and split files) for two projects and measured execution time and resource usage of renku metadata storage. Since we don't have an implementation that uses custom metadata format, these measurements show only data storage in JSON-LD format. The execution platform is a MacBook Pro laptop with a 2.7 GHz Quad-Core Intel Core i7 processor, 16 GB of memory, and SSD running macOS Catalina. Python version is 3.7.9. Execution time and memory usage are reported using `time -l` command: (e.g. `/usr/bin/time -l python3 -c 'import renku ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_json(".renku/provenance.json", lazy=False) ;'`). We ran each experiment twice and reported the second execution.

We report numbers for two modes of loading graph metadata: Load only Renku models (using Calamus) or load metadata directly into an RDF graph. Loading only Renku models is required when we want to update (add to) the graph while loading RDF is used for querying the graph. 

We also report numbers for updating the graph (i.e. Renku models). When splitting the graph across multiple files, the update is independent from the total graph size because we need to serialize a single file. When storing the graph in a single file, we need to read the whole graph, update it, and write it back.

# vomcases
Project [vomcases](https://github.com/mohammad-sdsc/vomcases) has ~9700 workflows. The following table shows provenance metadata analysis for this project:
||Size on Disk (MB)|Load Time - RDF (m:s)|Memory Usage during Load - RDF (GB)|Load Time - Renku Models (m:s)|Memory Usage during Load - Renku Models (GB)|Update Time (m:s)| Update Memory Usage (GB)|
|-|-|-|-|-|-|-|-|
|**Single-File**|136|1:20|1.1|28:38|0.8|33:06|4.2|
|**Split Files**|1000|9:50|1.7|5:30|1.0|0:02|0.08|

**Notes**
- Storing data in a single file for this project is already hitting the storage limit for github (max file size of 100 MB) and gitlab (10 MB; seems to be reconfigurable).
- We should avoid loading the RDF data for common operations by using some sort of caching (e.g. files were last updated by which workflows).
- Loading multiple smaller files using calamus is way faster than loading a large file.

# covid-19-public-data
The following table shows provenance metadata analysis for the [covid-19-public-data](https://dev.renku.ch/gitlab/mohammad.alisafaee/covid-19-public-data.git) project that has 239 workflows:
||Size on Disk (MB)|Load Time - RDF (m:s)|Memory Usage during Load - RDF (GB)|Load Time - Renku Models (m:s)|Memory Usage during Load - Renku Models (GB)|Update Time (m:s)| Update Memory Usage (GB)|
|-|-|-|-|-|-|-|-|
|**Single-File**|4|0:04|0.13|0:07|0.11|0:12|0.16|
|**Split Files**|16|0:11|0.12|0:08|0.1|0:02|0.08|

# Commands
Graph generations and these experiments are using https://github.com/SwissDataScienceCenter/renku-python/pull/1806 with https://github.com/SwissDataScienceCenter/renku-python/pull/1934 cherry-picked on top of it. We use the following commands for the experiments:

**Single File**
- Load RDF:
```/usr/bin/time -l python3 -c 'import renku ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_json(".renku/provenance.json", lazy=True) ; pg.rdf_graph ;'```
- Load Renku models:
```/usr/bin/time -l python3 -c 'import renku ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_json(".renku/provenance.json", lazy=False) ;'```
- Update:
```/usr/bin/time -l python3 -c 'import renku ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_json(".renku/provenance.json", lazy=False) ; pg.to_json("single-no-lazy.json") ;'```

**Split Files**
- Load RDF:
```/usr/bin/time -l python3 -c 'import renku ; import pathlib ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_provenance_paths(pathlib.Path(".renku/provenance").glob("*json"), lazy=True) ; pg.rdf_graph ;'```
- Load Renku models:
```/usr/bin/time -l python3 -c 'import renku ; import pathlib ; pg = renku.core.models.provenance.provenance_graph.ProvenanceGraph.from_provenance_paths(pathlib.Path(".renku/provenance").glob("*json"), lazy=False) ;'```
- Update:
vomcases: ```/usr/bin/time -l python3 -c 'import renku ; a = renku.core.models.provenance.activity.ActivityCollection.from_json(".renku/provenance/00b46b6fbe5e463787b252c7511e0eac_python3.json") ; a.to_json("multiple-no-lazy.json") ;'```
covid-19-public-data: ```/usr/bin/time -l python3 -c 'import renku ; a = renku.core.models.provenance.activity.ActivityCollection.from_json(".renku/provenance/e1fec33cff4541eb8ebdee9da5ee8e52_papermill.json") ; a.to_json("multiple-no-lazy.json") ;'```

**Comment by Panaetius** [comment]
`renku graph export` takes a `--revision` flag now
