### ISSUE TITLE
chore: fix the renku-python version used in the core service

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1743]
At the moment, because the core service docker container runs a command that modifies the state of the repo, the version of the service is `0.x.y-dirty` - this looks particularly bad now with migrations implemented in the UI - see, for example:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/3353586/99670155-61c5f880-2a70-11eb-95b8-31321b06cf8e.png">

There is no need to pollute the repo in the container - we can either not use the requirements builder or we can export the requirements file to a temporary path outside the repo before installing.

**Comment by Panaetius** [comment]
We should change that e.g. on renkulab.io it's `0.12.1.dev0+dirty`. 

`0.12.2.dev2+dirty` should be `0.12.2.dev2` but the dev2 part is correct on the dev deployment. Since it's automatically deployed from master and we push prereleases, I think allowing dev users to migrate to e.g. 0.12.2.dev2 makes a lot of sense for easily testing new things.

So I'd get rid of having `+dirty` and remove `dev0` but otherwise leave it unchanged.
