### ISSUE TITLE
handle globs in renku dataset add

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#181]
We should do something with e.g.

```
renku dataset add ../path/to/data/*
```

cc/ @lusamino

**Comment by lusamino** [comment]
Precisely, and then get inside `<renku_folder>/data/<name_dataset>/` all the different folders, or files, contained into `../path/to/data/`. And this is different from the current approach, because currently we get in  `<renku_folder>/data/<name_dataset>/` the folder we refer to, while with the new enhancement we will get all folders or files inside it.
