### ISSUE TITLE
Return more finegrained Dockerfile update information in service

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2048]
Currently, the service just returns `docker_update_possible` True/False.

But `False` can mean 3 things:
- The Dockerfile is up to date
- The Dockerfile doesn't contain an `ARG ....` line
- There is no Dockerfile

We should differentiate these cases and return finegrained information in the service, so the Ui can show different messages to the user depending on the case.

**Comment by ciyer** [comment]
I think the entire structure of the information returned by the endpoint should be changed to be clearer and avoid confusion.

The current data looks like this:
```
{
	"result": {
		"project_supported": true,	
		"latest_version": "0.14.2",   
		"project_version": "0.14.0",  // from the metadata.yml file
		"automated_template_update": false,
		"docker_update_possible": true,
		"template_update_possible": true,
		"template_source": "https://github.com/SwissDataScienceCenter/renku-project-template",
		"current_template_version": "73db625bf5d9effa1d76a4e5e1fcbcb1a927f654",
		"latest_template_version": "817b03c0f434a79eb54473688c1f897a66228b3d",		
		"template_ref": "master",
		"migration_required": false,
		"template_id": "python-minimal"
	}
}
```

It should have a clearer structure to make it easier to work with:
```
{
	"result": {
		"project_supported": true,
		"core_service_compatibility_status": {
			"migration_required": false,
		},
		"dockerfile_renku_status": {
			"newer_renku_available": true,        // docker_update_possible -> newer_renku_available
			"automated_dockerfile_update": true,  // new field
			"latest_version": "0.14.2",
			"project_version": "0.14.0",          // from the dockerfile
		},
		"template_status": {
			"automated_template_update": false,
			"newer_template_available": true,    // template_update_possible -> newer_template_available
			"template_source": "https://github.com/SwissDataScienceCenter/renku-project-template",
			"current_template_version": "73db625bf5d9effa1d76a4e5e1fcbcb1a927f654",
			"latest_template_version": "817b03c0f434a79eb54473688c1f897a66228b3d",		
			"template_ref": "master",
			"template_id": "python-minimal"
		}
	}
}
```

**Comment by vfried** [comment]
I think we should do somehting like this to make things a bit more clear....
|    |                                                                                                 | MIGRATION STATUS                   | ACTION/MESSAGE                                                               |
|----|-------------------------------------------------------------------------------------------------|------------------------------------|------------------------------------------------------------------------------|
| 1  | migration_required T project_supported T newer_renku_available T automated_dockerfile_update T  | NEEDED                             | AUTOMATIC MIGRATION (DOCKER + METADATA)                                      |
| 2  | migration_required T project_supported T newer_renku_available T automated_dockerfile_update F  | NEEDED                             | AUTOMATIC METADATA MIGRATION + MANUAL DOCKER UPGRADE?                        |
| 3  | migration_required T project_supported T newer_renku_available F automated_dockerfile_update T  | NEEDED (IS THIS CASE POSIBLE?)     | AUTOMATIC METADATA MIGRATION + NO DOCKERFILE UPGRADE                         |
| 4  | migration_required T project_supported T newer_renku_available F automated_dockerfile_update F  | NEEDED (IS THIS CASE POSIBLE?)     | AUTOMATIC METADATA MIGRATION + DOCKERFILE UP TO DATE                         |
| 5  | migration_required T project_supported F newer_renku_available T automated_dockerfile_update T  | NEEDED                             | MANUAL METADATA MIGRATION + AUTOMATIC DOCKERFILE UPGRADE                     |
| 6  | migration_required T project_supported F newer_renku_available T automated_dockerfile_update F  | NEEDED                             | MANUAL METADATA AND DOCKERFILE UPGRADE                                       |
| 7  | migration_required T project_supported F newer_renku_available F automated_dockerfile_update T  | NEEDED (IS THIS CASE POSIBLE?)     | MANUAL METADATA MIGRATION + DOCKERFILE UP TO DATE                            |
| 8  | migration_required T project_supported F newer_renku_available F automated_dockerfile_update F  | NEEDED                             | MANUAL METADATA MIGRATION + DOCKERFILE UP TO DATE                            |
| 9  | migration_required F project_supported T newer_renku_available T automated_dockerfile_update T  | RECOMENDED                         | METADATA UP TO DATE + AUTOMATIC DOCKERFILE UPDATE                            |
| 10 | migration_required F project_supported T newer_renku_available T automated_dockerfile_update F  | RECOMENDED                         | METADATA UP TO DATE + MANUAL DOCKERFILE UPGRADE                              |
| 11 | migration_required F project_supported T newer_renku_available F automated_dockerfile_update T  | NO NEED                            | METADATA UP TO DATE + DOCKERFILE UP TO DATE                                  |
| 12 | migration_required F project_supported T newer_renku_available F automated_dockerfile_update F  | NO NEED (IS THIS CASE POSIBLE?)    | METADATA UP TO DATE + DOCKERFILE UNKNOWN SINCE IT'S NOT COMPATIBLE           |
| 13 | migration_required F project_supported F newer_renku_available T automated_dockerfile_update T  | RECOMENDED (IS THIS CASE POSIBLE?) | METADATA IS AHEAD OF DEPLOYMENT + DOCKERFILE AUTOMATIC MIGRATION             |
| 14 | migration_required F project_supported F newer_renku_available T automated_dockerfile_update F  | RECOMENDED                         | METADATA IS AHEAD OF DEPLOYMENT + MANUAL DOCKERFILE UPDATE                   |
| 15 | migration_required F project_supported F newer_renku_available F automated_dockerfile_update T  | NO NEED (IS THIS CASE POSIBLE?)    | METADATA AHEAD OF DEPLOYMENT + DOCKERFILE UP TO DATE                         |
| 16 | migration_required F project_supported F newer_renku_available F automated_dockerfile_update F  | NO NEED (IS THIS CASE POSIBLE?)    | METADATA AHEAD OF DEPLOYMENT + DOCKERFILE UINKNOWN SINCE IT'S NOT COMPATIBLE |

**Comment by ciyer** [comment]
> My notes on this:
> 
> * I would change the name of core_service_compatibility_status to metadata_compatibility_status since I think this refers to the version of the metadata

From the perspective of the UI, all we want to know is can the core-service operate on this project. We do no care why it can or cannot, so I think it is better the leave the details out. 

> * currently, latest_version and project_version were referring to the metadata version and not the dockerfile version, from my point of view it makes sense to receive also the versions of the metadata and display them but to make a division between dockerfile and metadata versions.

I looked into this, and it is not the case. The metadata version is some number (e.g., 5) that has no meaning anywhere else, so I think we can ignore it on the UI. The `project_version` currently is, I believe, the version of renku-python that was used to write the `metadata.yml` file. This is also irrelevant. I think the important information is which version of Renku do I get if I launch a session on this project: that is the Dockerfile Renku version. 

> As a final comment, I think besides redefining variables we should review the way we are using them...
> 
> * if migration is possible but dockerfile migration isn't --> should we migrate metadata and advice users to migrate the dockerfile manually?

I do not think we ever want to give the user the choice to upgrade just the metadata from the UI. Doing so breaks the project since the Renku version in the Dockerfile is out of sync with the version of the metadata. If an update of the Dockerfile is not possible automatically, then we give the user the manual instructions. 

> * if migration is not possible, but dockerfile upgrade is... should we make them upgrade the dockerfile only or would this make thing incompatible?
>
> * same for when the project is not supported but the dockerfile can be upgraded, I think we should make a chart of when we can upgrade and when not

These are good questions. I would think that neither of these can actually happen, but someone from rp should confirm that.

**Comment by Panaetius** [comment]
> if migration is not possible, but dockerfile upgrade is... should we make them upgrade the dockerfile only or would this make thing incompatible?

This is the case when no metadata changes were made in renku-python. Upgrading the Dockerfile is optional in this case, but I see no reason why not to, as it might still contain bugfixes that are good to have.

> same for when the project is not supported but the dockerfile can be upgraded, I think we should make a chart of when we can upgrade and when not
project not supported means it was made with a newer version of renku than what the service has (let's say 0.15). If the service is at 0.14 but the Dockerfile is at 0.13, then you'd see this. Upgrading the Dockerfile would set it to 0.14, project would still not be supported, but the project wouldn't be any more or less broken than it was before.
