### ISSUE TITLE
Improve/tweak split files approach

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2073]
Finish evaluating the approach started in https://github.com/SwissDataScienceCenter/renku-python/issues/1732

**Comment by mohammad-sdsc** [comment]
In split files approach, we store a single provenance file (an ActivityCollection to be precise) when executing run, rerun, or update commands. This is similar to what we currently do when storing Provenance Graph in multiple files but instead of using Calamus for JSON-LD serialization we use plain marshmallow schemas with JSON serialization (i.e. custom format). A base marshmallow schema class adds a `post_dump` hook to include id and type information after serialization. It also has a `post_load` hook to create an instance of a model after deserialization. We store this metadata in gzip format using Python's built-in `gzip` module.

Profiling deserialization of Provenance Graph shows that most of the time is spent in marshmallow:

```
      ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1294115/9722    9.367    0.000   91.571    0.009 schema.py:586(_deserialize)
4167386/9722    4.037    0.000   91.428    0.009 fields.py:330(deserialize)
1099707/9722    4.027    0.000   92.308    0.009 schema.py:810(_do_load)
      830551    3.575    0.000    5.014    0.000 fields.py:148(__init__)
     1235777    3.129    0.000   17.129    0.000 custom.py:118(make_instance)
    21704908    3.017    0.000    4.405    0.000 {built-in method builtins.isinstance}
      191393    2.897    0.000   11.066    0.000 schema.py:947(_init_fields)
     9458435    2.448    0.000    2.448    0.000 {built-in method builtins.getattr}
        9722    2.316    0.000    2.316    0.000 decoder.py:343(raw_decode)
      191393    2.137    0.000   24.269    0.000 schema.py:367(__init__)
...
```

As an optimization, I wrote a custom deserialize function that reads the custom JSON format and creates Python objects using provided type information (https://github.com/SwissDataScienceCenter/renku-python/blob/684a35d06e712bcc7d85593d3a86f3efe63acdc2/renku/core/models/custom.py). Note, that we don't need to optimize serialization because we serialize one object once in a while (after each run, rerun, or update command).

The following tables compares storage requirements and time for loading Provenance Graph for a project with ~10K workflow files (https://github.com/mohammad-sdsc/vomcases). It compares the current approach (using Calamus), new custom format, and new custom format with optimized deserialization:

||Size on Disk (MB)|Load Time (m:s)|
|-|-|-|
|Current|1000|5:30|
|Custom|75|1:05|
|Custom with optimized deserialization|75|0:11|

**Comment by Panaetius** [comment]
Superseeded by https://github.com/SwissDataScienceCenter/renku-python/issues/2110
