### ISSUE TITLE
improve JSON-RPC error codes

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2100]
Some of the error codes returned by the renku core service could be improved. For example, from the JSON-RPC 2.0 spec:

* code -32000 --> generic server error
* code -32601 --> method does not exist

We use -32000 for a very specific server error - to indicate that something is wrong with git repository access. We also use it to indicate a generic HTTP server error. 

We use -32601 to indicate that the request headers were wrong (typically because authentication headers are missing) but this error code is for trying to use non-existent methods. We should probably use -32602 (invalid parameters) in this case. 

In addition, since JSON-RPC allows a lot of flexibility to define custom errors, we should understand where the most frequent failures are occurring and provide more informative errors - at the moment, all that is returned is `-32000 - internal error`. 

This is a follow-up to #2056.

**Comment by vigsterkr** [comment]
as a sidenote/task: unify the definitions of error codes, see for example `-32603` is defined in two different places:
```
renku/service/config.py:INTERNAL_FAILURE_ERROR_CODE = -32603
renku/service/views/apispec.py:INTERNAL_FAILURE_ERROR_CODE = -32603
```

**Comment by Panaetius** [comment]
I think there's 3 kinds of errors:
- ones a user can recover from
- ones the client (UI in our case) can automatically recover from
- ones they can't do anything about (i.e. Bugs)

or more basically just the difference between expected and unexpected errors.

Whatever we decide on, we have to think about who the recipient is and what they will do with the error, and tailor our solution towards that. The errors should serve some purpose and expected errors should be documented in the api.

An example of the slack api errors can be found in the "Errors" list on https://api.slack.com/methods/admin.apps.uninstall . I think something along these lines would be great to have.

**Comment by Panaetius** [comment]
Right now we use JSON-RPC error codes but we don't have a JSON-RPC API. This doesn't make sense to me, especially since something like `-32600 | Invalid Request | The JSON sent is not a valid Request object.` in the JSON-RPC spec but if we receive malformed JSON flask would return a 400 HTP error code instead due to the `BadRequest` error handling.

I don't think we're going to change our API model anytime soon, and I'm also not sure how much we gain from adopting JSON-RPC for one part of the API (Error handling) but nothing else, as it might be confusing to clients to mix and match styles.

We should define proper errors for each endpoint and document them as such, and return all these errors in a consistent format. I think HTTP errors for generic errors like endpoint not found is ok, but for everything that actually happening inside our application/code, we should have a single way of dealing with errors.

For the non-HTTP errors, we should have one or more generic errors for when things go horribly wrong. Like generic unhandled error in core module, generic unhandled error in service controller (Think HTTP 500). But we should also have expected errors like `dataset_not_found` on `/datasets.edit`  and document those, so a client can handle them properly. That said, a pre-defined string label should suffice and I think an error code is just an additional layer of abstraction that isn't needed for these cases.

I'll write an RFC based on the guidelines outlined in this post.
