### ISSUE TITLE
renku rm a data folder

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#2315]
## Describe the bug
running `renku rm data/data-folder` led to the following message. The dataset was removed with renku already around a month ago. This worked fine for two other data-folders.

There is a warning, that there are custom `.gitattributes`.

## Details
**Renku version:** 0.16.0
**OS:** Linux (#29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021)
**Python:** 3.8.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 123, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 89, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/remove.py", line 36, in remove
    remove_command().with_communicator(communicator).build().execute(sources=sources, edit_command=click.edit)
  File "[...]/renku/core/incubation/command.py", line 132, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/remove.py", line 76, in _remove
    if communication.confirm('Do you want to edit ".gitattributes" now?', default=False):
  File "[...]/renku/core/utils/communication.py", line 204, in wrapper
    return f(*args, **kwargs)
TypeError: confirm() got an unexpected keyword argument 'default'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
Thank you for reporting this. This is a bug in code, not something wrong in your repository.

`renku rm` does several things, like removing the files from datasets they're inside (So no need for `renku dataset rm` first), then updating git lfs and then removing the files from git.

This bug happens in the second stage, where it removes the files from git lfs and then double-checks that they're not in gitattributes anymore. If the removed files are still matched by some rule in gitattributes after renku tried to remove the corresponding rules, it'll prompt you if you want to manually edit .gitattributes . And this prompt fails for a stupid reason.

So there's not really anything wrong, the dirty .gitattributes is because renku already modified it, which is fine. You should have a look in the gitattributes file to see if there are still any filters/rules that match the files you want to remove and edit them accordingly. Once you're happy with the gitattributes file, do a `git rm -rf data/data-folder`, and commit everything. This is what `renku rm` would have done had it not failed.

**Comment by LiliGasser** [comment]
Thank you for your detailed and clear explanation. It worked smoothly and I'll use only `renku rm` in the future.
