### ISSUE TITLE
Removed files still shown as outdated

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#2802]
**Describe the bug**
I removed some files, but renku status still sees these as outdated outputs. 

**Link to project**
https://renkulab.io/projects/remko.nijzink/budyko

**To Reproduce**
`renku status`
```
Outdated outputs(3):
  (use `renku update --all` to generate the file from its latest inputs)

	data/img/technical_paper/3_uncertainty.png: src_py/plot_uncertainty.py
	data/img/technical_paper/4_dist_aridity.png: src_py/plot_dist_aridity.py
	data/img_tech_note/4_dist_env.png: src_py/plot_dist_env.py

Modified inputs(3):

	src_py/plot_dist_aridity.py
	src_py/plot_dist_env.py
	src_py/plot_uncertainty.py

Deleted files used to generate outputs:

	src_flexsimple


```

**Expected behavior**
The files data/img/technical_paper/3_uncertainty.png and data/img/technical_paper/4_dist_aridity.png do not exist anymore and should not be shown.

**Run environment (please complete the following information):**
 - renku-python version 1.1.4
 - Python version 3.8.5
 - local terminal

**Comment by mohammad-sdsc** [comment]
This use-case affect both `status` and `update` commands. The `rerun` command is not affected since we specify a path to be regenerated and all of its upstream paths should be regenerated as well even if they are deleted.

A proper solution for this use-case would be to delete plans/activities that generate those paths so that they won't be updated. Right now, it's possible to delete plans but not activities.

I suggest we keep the default behavior and add  a `--ignore-deleted` flag to avoid reporting deleted files. We also add a `update_ignore_deleted` config so that users can make this the default behavior on a project/global level.

Deleted files will be ignored if all of their siblings and downstream is deleted as well. This means that if one of the siblings still exists or an existing file depends on a deleted file, the deleted file will not be ignored. Note that this use-case only applies to generated files: Deleted inputs are always reported as deleted.
