### ISSUE TITLE
`renku session ls` fails if only local docker session is active

### ISSUE THREAD

**Issue by calyptis** [SwissDataScienceCenter/renku-python#3253]
**Describe the bug**
Having had logged into Renku & started a local session, the command `renku session ls` returns an error saying:

`Error: Please run the renku login command to authenticate with Renku or to refresh your expired credentials.`

**Link to project**
https://renkulab.io/projects/lucas.chizzali/leafsim/

**To Reproduce**
1. `renku login --git https://renkulab.io`
2. `renku session start`
3. `renku session ls`

**Expected behavior**
When running `renku session ls -p docker`, I get the expected output:

```
ID               STATUS   URL
----------  --------  ------------------------------------------------------------
...                running   http://0.0.0.0:50444/?token=...
```

**Run environment (please complete the following information):**
 - renku==2.0.1
 - Python 3.9.15
 - local terminal

**Comment by mohammad-alisafaee** [comment]
This is expected behavior for renkulab provider if the token is expired. However, it shouldn't prevent other providers from listing their sessions (see #2961).

**Comment by Panaetius** [comment]
@mohammad-alisafaee  yes but it's literally, you `renku login` and then immediately run the command and this happens. It is due to the token expiring/not existing, but the root cause is that `renku login` does not do the same steps as a login in the UI and doesn't create a new token. The only fix for the user is to manually log in on the renku platform and then `renku login` on the CLI works properly again.

In the UI, if the token is expired/doesn't exist, the gateway returns a 403 and the UI fully logs out the user and redirects to the login page, which in turn fixes this when the user logs in again. The CLI should behave the same way.
