### ISSUE TITLE
update workflow Run template steps when a file is moved

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#445]
**Is your feature request related to a problem? Please describe.**
`renku mv` should update the relevant workflow steps to use the new file location

**Describe alternatives you've considered**
cursing every time `renku update` fails after I move a file

**Comment by rokroskar** [comment]
With #1545 this does indeed become optional.

**Comment by Panaetius** [comment]
@mohammad-sdsc What's your take on this?

**Comment by mohammad-sdsc** [comment]
Updating workflows is done in https://github.com/SwissDataScienceCenter/renku-python/pull/1249 for files that belong to a dataset.
I agree that we don't need to do this once #1312 is done because users can modify workflow template (or delete and create a new one). 

Actually, we don't need `renku mv` anymore once #1249 is merged.

**Comment by mohammad-sdsc** [comment]
This is implemented in https://github.com/SwissDataScienceCenter/renku-python/pull/1249 but requires rebasing and incorporating new changes to workflows.

**Comment by Panaetius** [comment]
Closed in favor of #711
