### ISSUE TITLE
cli: renku worklow annotations

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#459]
Add annotation to CWL tools.

```console
$ renku workflows annotate <name|uuid> <key> [<value>|stdin|--edit]
```

https://www.commonwl.org/user_guide/17-metadata/

---
cc @schymans @rcnijzink

**Comment by rokroskar** [comment]
This can be done similarly to the implementation of the plugin mechanism in #883 - @Panaetius?

**Comment by Panaetius** [comment]
Everything can be done similar to the implementation of the plugin mechanism!

More seriously, that plugin hook allows adding arbitrary annotations when doing `renku run`, so exactly the same thing can be done here, but you couldn't use the plugin hook directly. Just create the annotation object itself and add it to a workflow, serializing the annotations into the cwl file is supported already from the other change.

**Comment by rokroskar** [comment]
> Just create the annotation object itself and add it to a workflow, serializing the annotations into the cwl file is supported already from the other change.

yes exactly - my point was more that we can/should use the metadata extension in the same way and figure out how to serve this additional data from the graph queries.

**Comment by schymans** [comment]
Would it be possible to give a code snippet as example how to achieve this? Just in case someone finds this issue when looking for a way to annotate a workflow.

**Comment by Panaetius** [comment]
We are heavily overworking how the workflow system works, so many things will change. 

This issue was closed because it's about adding annotations to the internally stored .cwl files that were used for workflows, but we've moved away from storing cwl files for almost a year now so it wasn't really relevant anymore.

That said, the current way of adding custom metadata to a workflow (in the knowledge graph) is by writing a plugin for it, https://github.com/ratschlab/renku-mls/blob/master/renkumls/plugin.py is an example of such a plugin. Though the plugin hooks will change a bit as part of this big workflow overhaul.

We also want flags for `renku run`, `renku dataset create`, `renku dataset edit` and for projects as well, such as `--metadata <file containing custom jsonld metadata>` that add the metadata contained in the file to the knowledge graph, since not everyone has the time to develop a plugin 😅 

As for adding annotations to cwl files, in the future renku will have a `renku workflow export --format <format>` command that can support plugins for exporting renku workflows as CWL and other formats, and we might consider adding a flag there as well to add metadata to the exported files, but that would really be up to the exporter plugin (not every workflow language supports annotations).
