### ISSUE TITLE
Display `renku` in CLI version info

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-python#559]
To match the behavior of `git` and `git lfs`
![image](https://user-images.githubusercontent.com/4173925/59976799-8f7fe700-95c9-11e9-8f0b-83ef5b0df678.png)
could we display
```
$ renku --version
renku 0.5.0
```
instead of
```
$ renku --version
0.5.0
```
?

**Comment by jsam** [comment]
Since we are not using versioning suits, what value do we get with just adding 'renku' string as a prefix?

One thing which we could think about, which would possibly be useful is adding release tags or commit hash as a suit. But since most people are installing from PyPI (where that version tag is published), it's not that difficult to figure that out.
