### ISSUE TITLE
Dataset tagging

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#566]
Currently, there is no support for automated versioning of datasets created and managed within renku. A field for versioning is there, but it's only used for import/export features. We should come up with renku way of versioning of datasets so we could automate and build support around versioning of datasets.

This feature would be needed also for building additional support for versioning datasets during export to Zenodo (and other providers).

**Comment by Panaetius** [comment]
# Design Proposal
## Version Format

Use semver, as it's easy to grasp for users. Automatically bump minor version but allow the user to manually bump major version. Version strings are of the form "<major>.<minor>@<commit>", e.g. `1.0@b9da310d04e1c5e79272d2ace73d1c3713fd4a1d`. For the current version, `<commit>` could be empty or `HEAD`, as we don't know the commit sha ahead of committing.

## Version Tracking/Bumping
Several possibilities exist here, it depends a bit on what we want to accomplish.
### Easy Implementation
have a command like `renku dataset bump-major-version <name> ` that increases major version by one and sets minor version to 0 and commits the change.
Automatically increase minor versions when the dataset is modified (metadata change, adding/editing/deleting files).

But then if I bump the major version from 1.9 to 2.0, both those versions would have identical content apart from the version, which goes against the idea of versions

### Complex Implementation
All commands that can change a dataset should have a `--major` flag that will bump the major version at the same time as modifying the dataset. Without the flag, the minor version is bumped instead.

### Non-automated versioning
Versioning is up to the user, we add a `renku dataset version [bump-major | bump-minor] <name>` command or similar and create a new commit when changing the version, with all changes since the last version change being considered part of this new version. We don't automatically adjust the version when doing any renku commands and changes since the last version bump are considered dirty/not part of a version.

**Alternative**: *With this approach, we don't actually have to enforce semver and we could support arbitrary strings as versions, `<user-string`@<commit>` and just let users chose what versioning scheme to follow. That would mean we could just take versions from imports whichever way the provider handles them, but we'd have to set the initial version of a dataset to `''` if not otherwise specified.*

I think this would mirror how versions are used in Zenodo, for example, and map nicely to users conceptions, but it'd mean that the `version` field on a dataset doesn't hold any renku specific meaning. It also make implementation a lot easier and less error prone.

## Knowledge Graph
Versions should be represented in the KG somehow. As discussed in https://github.com/SwissDataScienceCenter/renku/issues/642 one way of doing this is to have an abstract `Concept` object that uses PROV-O to refer to concrete version instances. That would fit well with the PROV-O vocab but it'd mean we have to save (or worse, construct at load) all versions of a dataset to the KG, littering it with entries that don't really matter in a lot of cases.  An alternative would be to have a `versionEntry` type and have a list of all versions of a dataset as `dataset.versions` (or `dataset.previous_versions`) using `schema:hasPart`, which each one only saving the version string + commit and possibly creation date. We can still use PROV-O to link those entries, but without duplicating the whole dataset entry. Plus with the commit sha in the version we can get the dataset state of a version as well without duplication. Though I'm not familiar enough with JSON-LD to know if having different properties that map to `hasPart` are allowed.

**Comment by rokroskar** [comment]
How about a mix between "non-automated" and "alternative"? What I mean is that if someone doesn't want to think about versioning, we can document the use and benefits of semver - otherwise they are free to cook up their own versioning scheme. In the KG it would be all the same - we record the `specializationOf` and `wasRevisionOf` to express versions and the actual version naming doesn't matter so much.

**Comment by Panaetius** [comment]
Yes I think that would make a lot of sense and it should be easy to implement both

**Comment by jirikuncar** [comment]
IMHO simple automatic incremental numbering makes sense anytime you change (meta)data and add "DOI tags" anytime the dataset is published. SemVer makes more sense for software as it is not very clear how you describe "backward compatible dataset versions".

**Comment by rokroskar** [comment]
> SemVer makes more sense for software as it is not very clear how you describe "backward compatible dataset versions".

True - what I was thinking here was to use something SemVer-like in the sense that if the metadata changes it's not a "breaking change" but if the data changes it is. Maybe that's making it too complicated but I was trying to avoid a situation where someone tweaking a description would end up with dataset version 50.

**Comment by rokroskar** [comment]
How do you automatically increment a version for which you have no schema? If a dataset comes with a version as a string that is not in semver format, we have to assume that the user will set the version by hand IMO. 

For versioning in workflows versions are not needed since everything is committed to git anyway. "Versions" here are just some sort of human-readable convenience.

**Comment by Panaetius** [comment]
how would we handle automated increment of arbitrary versions? I mean, the version in zenodo could be `1.1-alpha`, `0.1-pre4-dev`, `rolling-giraffe` or what have you. 
And not every single change necessarily means an increase in version, you might want to add a file and edit metadata to constitute one new version, otherwise we might get meaningless in-between versions.

As I see it, we can either adopt a fixed scheme in renku and have versions from external providers in a separate field, automatically incrementing the renku-specific field only, or use one field for both but without automated incrementing. There's just too many versioning schemes that we could support and differentiate them all and it'd be a nightmare to support.

Zenodo supports arbitrary strings as versions. Dataverse enforces `major.minor` semver.

**Comment by jsam** [comment]
> How do you automatically increment a version for which you have no schema? If a dataset comes with a version as a string that is not in semver format, we have to assume that the user will set the version by hand IMO.
Well, we are discussing 2 options which are most occurring one, so inferring the schema is not a problem.

> For versioning in workflows versions are not needed since everything is committed to git anyway. "Versions" here are just some sort of human-readable convenience.
IMHO, I'm pretty sure that there will be a request that instead of specifying dataset commit hash in workflow input, that you specify "human-readable" version.

**Comment by jsam** [comment]
> how would we handle automated increment of arbitrary versions? I mean, the version in zenodo could be `1.1-alpha`, `0.1-pre4-dev`, `rolling-giraffe` or what have you.

1) and 2) is easy to handle. 3) never seen in the wild so I'm not sure.

> And not every single change necessarily means an increase in version, you might want to add a file and edit metadata to constitute one new version, otherwise we might get meaningless in-between versions.

Every dataset action which creates a commit is basically an increment of the version.

> 
> As I see it, we can either adopt a fixed scheme in renku and have versions from external providers in a separate field, automatically incrementing the renku-specific field only, or use one field for both but without automated incrementing. There's just too many versioning schemes that we could support and differentiate them all and it'd be a nightmare to support.
> 
> Zenodo supports arbitrary strings as versions. Dataverse enforces `major.minor` semver.

I agree. We should start with semver and go from there if there will be need.

**Comment by rokroskar** [comment]
Less is definitely more here. Do not underestimate people's creativity - we will never be able to parse and automatically increment all arbitrary string versions. Also people might have strong opinions about what the next version after `0.1-pre4-dev` should be and they may be different from yours so just let them call it whatever they want. 

I think @Panaetius has a good suggestion that when we get a version from a provider like zenodo we keep it, but we also give it an internal version, which should be based on `major.minor`. That way we don't have to handle datasets in a special way once they are in a renku project.

**Comment by Panaetius** [comment]
But let's say we support just semver for starter. 

A user import a dataset version `1.1` from Zenodo. He adds a file, edits metadata, adds another file, edits metdadata again. Versions is now `1.5`, automatically incremented.

The user wants to publish back to Zenodo, CLI asks "Do you want to publish version 1.5?" and the user is "No, this should be version 1.2", he edits the metadata to reflect that on the current instance of the dataset and publishes it to Zenodo.

Now he lists all versions of the dataset locally and he gets:
- 1.1
- 1.2
- 1.3
- 1.4
- 1.2

with `1.2` being there twice. Or do we prohibit setting the version manually to 1.2? In which case we could not fulfill the users intent. 

I just don't see a way of automating version increments and supporting imports&exports at the same time that is consistent and supports the requirements of different users.

**Comment by jsam** [comment]
Yes, I agree with that. I'm just saying that it might be confusing when you export and that version field is the same as the imported one, even though you worked on the dataset (so we should just keep that in mind).

I added this to my comment above:
`And if the version is not part of our supported schemas, we can change the imported version to default renku version and when you export we use renku default (of course with users warning/consent).`

**Comment by rokroskar** [comment]
I don't see any reason to automatically increment versions - that's what git is for. If the version here is to be a human-readable convenience, it should be a conscious choice of the user to change it.

**Comment by rokroskar** [comment]
Of course on export we could offer to automatically increment to something sensible.

**Comment by jsam** [comment]
Ok. Well, if I will not be able to reference a dataset by human-readable version in my workflows then there is not a lot of value of doing this if versioning is only being implemented for the export part. A simple dialog will do the trick.

**Comment by rokroskar** [comment]
I'm not saying we should only change it on export - I just mean that it should be an action on the part of the user and not automatic. If you make changes and you want to reference the current state by a version number, then by all means bump the version and use that in other commands.

**Comment by jsam** [comment]
> I'm not saying we should only change it on export - I just mean that it should be an action on the part of the user and not automatic. If you make changes and you want to reference the current state by a version number, then by all means bump the version and use that in other commands.

You can do this already within the current renku.

**Comment by jsam** [comment]
So that would be something like docker tags approach?

**Comment by Panaetius** [comment]
As this seems to be a bit more involved than originally expected, should we do a meeting?

**Comment by rokroskar** [comment]
I think we agree on starting with simplified semver `major.minor` - I think we should wait with automation for now and provide manual means of bumping the versions
