### ISSUE TITLE
Output-directory needs to be empty

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#596]
When specifying an outputfolder, adding new files, or appending data to existing files lead to the error:

```
Error: The output directory "data/VOM_output/HowardSprings/freedrainage_cpcff1.0" is not empty.

Delete existing files before running the command:
  (use "git rm <file>..." to remove them first)

        data/VOM_output/HowardSprings/freedrainage_cpcff1.0/sce_bestpars.txt

Once you have removed files that should be used as outputs,
you can safely rerun the previous command.
```

Is there a way to avoid this? In this case, we are looping an optimization algorithm, which needs to be restarted on the HPC. It starts from the existing files, and appends new data to it. Eventually it writes a file with the final solution.

**Comment by hluetck** [comment]
I created a toy project that fully reproduces the issue: https://renkulab.io/projects/746/

The file [renku-workflow.sh](https://renkulab.io/gitlab/hluetcke/toy-project/blob/master/renku-workflow.sh) has the commands that I run. The [meta-script.sh](https://renkulab.io/gitlab/hluetcke/toy-project/blob/master/meta-script.sh) just copies `data.dat` from `~/toy-project/data/M1/Session1/raw/` to `~/toy-project/data/M1/Session1/preprocessed/`.  After
```
renku run /home/jovyan/toy-project/meta-script.sh /home/jovyan/toy-project/data/ /home/jovyan/toy-project/data/M1/Session1/raw/data.dat
``` 
I get the same error as above:
```
Error: The output directory "data" is not empty. 

Delete existing files before running the command:
(use "git rm <file>..." to remove them first)

data/M1/Session1/raw/data.dat

Once you have removed files that should be used as outputs, you can safely rerun the previous command.
```

**Comment by mohammad-sdsc** [comment]
Hi @rcnijzink,

Thanks for reporting this issue to us!

At the moment, it is not possible to mark a file both as input and output. The same is true for directories, and you cannot have input and output files in the same directory or subdirectories with a common root.

You can work around this limitation by putting your inputs and outputs in distinct files and directories.

**Comment by ableuler** [comment]
Hi @rcnijzink

You have pointed out a very fundamental issue here: Renku can not handle circular dependencies.

With Renku we're trying to record all steps of an analysis workflow in a dependency graph. Whenever an input of your analysis changes, we can then analyse this graph to figure out which parts of your analysis have to be re-executed and which parts will stay the same and thus don't have to be touched -- very similar to how `make` works. Just like in the case of `make`, this only works if the dependency graph is _acyclic_. Just imagine the same file being an in- _and_ output to a processing step. Whenever this processing step is run, it will immediately create a new version of the input file. Renku would detect this and try to re-run the processing step in order to update the outdated part of your pipeline, etc.

It is therefore not possible to have the same file or folder serve as input and output, or to have an output path which lies inside a directory already serving as an input. It _is_ possible to have inputs and outputs side-by-side in the same directory, see for example this [dummy project](https://renkulab.io/projects/764/files/lineage/data/ho.txt). For your example this means that instead of appending to an input file you will not get around writing to a new file instead.

We are trying hard to adapt Renku better to different ways in which people execute their work. For example, @mohammad-sdsc has added some nice features recently which allow for more flexibility in marking in- and outputs in ways other than treating them as command line arguments (#650, #598). But I don't think that we will be able to relax on the assumptions of _acyclic_ workflow dependencies. However, what we should do is document this limitation better.

I will therefore close this issue in favour of #656. Feel free to re-open it if you still feel that the `renku run` command does not behave according to what I have described above.

**Comment by rcnijzink** [comment]
Ok, thank you! I solved it by putting the inputs and outputs in different directories indeed. Instead of appending to a file, I copied the file to the output directory and appended new data there.

**Comment by rokroskar** [comment]
@rcnijzink the docs for these new flags mentioned by @ableuler are [here](https://renku-python.readthedocs.io/en/latest/cli.html#module-renku.cli.run) - see the bits describing `--input` and `--output`. There is now also away to simply produce a file that lists the paths which were used during the execution - see [here](https://renku-python.readthedocs.io/en/latest/cli.html#specifying-inputs-and-outputs-programmatically).
