### ISSUE TITLE
renku dataset ls

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#691]
**Is your feature request related to a problem? Please describe.**
The current command for showing the list of datasets that have been created is `renku dataset`, but I never remember that (especially because the helptext for `renku dataset` is "handle datasets").

**Describe the solution you'd like**
Since the command for listing dataset files is `ls-files` it would be more analogous to have the command `renku dataset ls` or `renku dataset list`, which was the command originally asked for (https://github.com/SwissDataScienceCenter/renku-python/issues/417).

**Comment by rokroskar** [comment]
We could add `renku dataset list` but still default to listing the datasets when `renku dataset` is called without arguments.

**Comment by emmjab** [comment]
I think instead of default listing the datasets when you call `renku dataset` it should print out help for all the subcommands of `renku dataset`

**Comment by emmjab** [comment]
Also -- same goes for `renku update` -- I think it should print out help for all the subcommands of `renku update`, one of which should be `all`, instead of by default updating all.
If you don't already know it's going to update everything, maybe you didn't want it to, and maybe you didn't know there were other subcommands.

**Comment by rokroskar** [comment]
Is this something we still want to do? cc @mohammad-sdsc

**Comment by emmjab** [comment]
related: https://github.com/SwissDataScienceCenter/renku-python/issues/1263

**Comment by Panaetius** [comment]
> Also -- same goes for `renku update` -- I think it should print out help for all the subcommands of `renku update`, one of which should be `all`, instead of by default updating all.
> If you don't already know it's going to update everything, maybe you didn't want it to, and maybe you didn't know there were other subcommands.

`renku update` does not have subcommands. 

In general:
- clone     shows help message
- config    shows current config
- dataset   lists datasets
- doctor*    executes doctor
- githooks  shows help
- help      shows help
- init*      executes init
- log*       shows log
- migrate*   executes migration
- mv        shows help
- rerun     shows help
- rm        outputs nothing?
- run       gives an error
- save*      Saves changes
- show      shows help
- status*    Shows status
- storage   shows help
- update    updates files
- workflow  lists workflows

I think the entries with * are fine since they don't have subcommands, and the ones that show a help are fine too. To keep things consistent, we'd need:
- config: show help, add `show` and `add`/`remove` subcommands
- dataset: show help, add `list` subcommand
- rm: Show help
- run: show help if there's no command
- update: I think this is fine, but adding a `--all` flag would probably be more consistent.
- workflow: show help/subcommands, add a `list` command

This would make all commands behave in a consistent way where we show help if nothing is specified and the command doesn't just do one thing
