### ISSUE TITLE
Finishing refactoring/cleanup on import/export commands

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#702]
Given that import and export commands are pretty heavy, and #676 was only the first step to make them more maintainable. As a developer, I would like to make them more readable and maintainable by breaking them down into smaller chunks and fully decoupled from click.

**Comment by Panaetius** [comment]
Things to pay attention to in particular:
- `export_dataset()` has `click` logic to prompt for an access_token, this shouldn't be in core, but in CLI instead
- Move progress-bar logic from `core/commands/dataset.py` to CLI
-change handle_duplicate_function so it doesn't have to check for duplicates itself but gets passed a boolean instead. and in in `renku/cli/dataset.py` for `write_dataset()`: Please move the part that checks for a duplicate (i.e. if client.load_dataset(name=name):) to core.

Additionally, in the vein vein but not restricted to `import` and `export`:
- in `renku/cli/dataset.py` change `with file_unlink(name, include, exclude) as records:` change to callback instead of context manager
