### ISSUE TITLE
Contract tests suite verifying json-ld output of renku log command

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#755]
As a Renku owner, I'd like to be sure that json-ld output generated by the `renku log` command does meet the contract for the Renku KG data.

Acceptance criteria:
* a suite of contract test verifying json-ld serialization of all types of entities meets the established contract.

**Comment by Panaetius** [comment]
As discussed on Slack, SHACL will be used to validate RDF/JSON-LD output

**Comment by Panaetius** [comment]
Similar to #547 and can be done at the same time

**Comment by Panaetius** [comment]
Tracking JSON-LD Issues:

- `rdflib-jsonld` is not maintained anymore (last commit 1 year ago) and should be replaced, possibly with `pyld`
- Old project metadata still uses `http://xmlns.com/foaf/0.1/Project'` instead of `http://schema.org/Project`, same with `schema:name` and `foaf:name`. This is handled/hidden by `jsonld.s` with the `translate` parameter, but there's no migration for it.
- Dataset Files can have invalid id's when filename contain colons `:`, e.g. `blob/9609b88114ac588ac815276d5ba6061590950bc2/data/Pyndl: Naive discriminative learning in python/pyndl-v0.6.0.zip`. Since the colon is unescaped, it is interpreted as an IRI instead of a node id. This leads to validation errors, though renku itself seems to work with it . Files with `:` in the name can't be added through `dataset add` (which itself seems like a bug, filenames should always be escaped in metadata...), but can come from imports. Plus previously imported datasets used `name` instead of `display_name`, so it can be a leftover of dataset names containing `:` which there is no migration for.
- Everything has a reference to project and as such project is in every json-ld graph. This should be replaced with an IRI instead of the full project data, for deduplication


...more to come ...

**Comment by rokroskar** [comment]
> This is handled/hidden by jsonld.s with the translate parameter, but there's no migration for it.

Why would you need a migration? The two are semantically equivalent.

**Comment by rokroskar** [comment]
> Everything has a reference to project and as such project is in every json-ld graph. This should be replaced with an IRI instead of the full project data, for deduplication

👍  - we should do this in other places too, e.g. `creator` - right now we are duplicating this metadata in a lot of places. One issue is that for properties like `creator` that are not at the top-level, it's not clear to me when or by whom the actual node (representing the creator) would be generated.
