### ISSUE TITLE
create a PoC using a pointer file to link to arbitrary external data

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#815]
As a Renku user, I would like to be able to create links to external data from my project and have those links lead to unambiguously identifying the data I am using in the Knowledge Graph. "External data" might be data on a shared filesystem or data that is located off-site. If the data is on a local, shared filesystem, the goal is to use the data without making copies.

One option is to use a "pointer file" that is saved to disk and which contains the information required to replace the pointer file with either a link to the data (if the data is accessible on a local filesystem) or the original raw data. This could be a very generic solution that could be adapted to a variety of backends (local/network storage, cloud storage/object store etc.)

If a pointer file is to be used, a decision must be made how the contents of the pointer file are to be swapped in both directions. One option would be to create custom git filters and rely on the same underlying functionality as git-lfs and similar systems. A demo of using a custom git filter with an arbitrary data server can be found here: https://gist.github.com/rokroskar/9fd57f2a6428c1ae8444972394fc10f9

The PoC should, however consider the simpler case of only linking to data on a local (shared) filesystem. There are a further two possible cases here: 1. the data is in a plain directory on a posix filesystem, and 2. the data is in a directory that is also a git repository. In the case of 1. we should compute the hash and use it as a part of the ID in the graph. In the case of 2. the hash and potentially other (renku-related) metadata can be obtained from the git repository.

**Comment by mohammad-sdsc** [comment]
Pointer file should work fine when we can download/copy the actual data to the repository. Git smudge filter can be used to retrieve the actual content of the file. Since the file is in the Git repo, everything works as before.

However, in the case of local/network storage, we don't want to copy the actual file to the repo and we want to just keep a symlink to the file location.

I've tried having a pointer file and replace it with a symlink upon checkout using a smudge filter (like the provided demo). The issue with this solution is that filtering is not supposed to change the file type and should only change its content; I am changing a normal file to a symlink which shows up as a change in Git and repo will be in a dirty state right after the checkout.

Here, `file.yml` is a pointer file containing a URI which is changed to a symlink by the filter (let's ignore the file exists error which does not cause any harm normally):
```
[~/playground/815]$ git status
HEAD detached at f4d2860
nothing to commit, working tree clean
[~/playground/815]$ git co master
running filter on file.yml
content: "b'uri: /home/mohammad/metadata.yml\n'"
error: unable to create file file.yml: File exists
T       file.yml
Previous HEAD position was f4d2860 gitattribute
Switched to branch 'master'
[~/playground/815]$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        typechange: file.yml

no changes added to commit (use "git add" and/or "git commit -a")
```

I could not find a workaround for this problem. Creating a symlink which points to a pointer file does not solve the issue either because smudge filter is not called on symlinks and we cannot change the symlink to point to the actual file upon checkout.

**Comment by rokroskar** [comment]
Thanks for looking into it @mohammad-sdsc - my feeling is that we should keep it simple, which means simply allowing users to make a link to a file somewhere on the filesystem. For files external to the system, the git filter approach might still make sense.

**Comment by mohammad-sdsc** [comment]
Basically, we need to answer these questions:
1. How to track an external file in a Git repo without copying it?
2. How to detect changes in such a file?
3. How to find commit history of changes to the file?   

I've ended up using two symlinks to address all these issues. When we first add a file to the dataset, the first symlink is created in the dataset's data directory that points to the second symlink. The first symlink's name is the same as the external file (or whatever name we pass with the `--destination` option). The second symlink resides in the dataset's metadata directory and points to the external file. It has a randomly generated name.
Upon detecting a modification to the external file, the second symlink is deleted and recreated with a new name; the first symlink is updated accordingly. This causes the first symlink to be committable as a changed file which makes it easy to find its changed in the Git history.
Detecting modification to the external file is done explicitly by running a `dataset update` command.

**Comment by mohammad-sdsc** [comment]
I've tried some other solution which did not work:

1. Using `--work-tree` option in Git to add files from the outside of the repo: It copies the file to the repo which is not what we want.
2. Keeping metadata about the external file in the dataset's metadata file: Finding file's changes in Git history will be difficult because we need to compare content of metadata file across various commits.
3. It is not possible to commit unmodified symlinks to git in order to keep track of changes in git history.
4. It is not possible to add version controlled metadata to files either.
