### ISSUE TITLE
Renku clone with no target path does not work

### ISSUE THREAD

**Issue by jeffallen** [SwissDataScienceCenter/renku-python#853]
**Describe the bug**
I tried to do `renku clone URL`, and it didn't work. I had to do `renku clone URL PATH` to get it to work.

```
icsil1noteb238:renku-python jallen$ renku clone git@renkulab.io:jeff.allen/testing.git
Cloning git@renkulab.io:jeff.allen/testing.git ...
Error: Cannot clone remote Renku project: git@renkulab.io:jeff.allen/testing.git

Traceback (most recent call last):
  File "/Users/jallen/work/renku-python/renku/core/management/clone.py", line 47, in clone
    url, path, recursive=recursive, depth=depth, progress=progress
  File "/Users/jallen/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/repo/base.py", line 1026, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/Users/jallen/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/repo/base.py", line 963, in _clone
    handle_process_output(proc, None, progress.new_message_handler(), finalize_process, decode_streams=False)
  File "/Users/jallen/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 124, in handle_process_output
    return finalizer(process)
  File "/Users/jallen/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/util.py", line 332, in finalize_process
    proc.wait(**kwargs)
  File "/Users/jallen/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 412, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --progress --recursive -v git@renkulab.io:jeff.allen/testing.git .
```

I could not find out how to get additional info from `git clone`, why was it's stderr thrown away?

**Desktop (please complete the following information):**
MacOS

**Comment by mohammad-sdsc** [comment]
Hi Jeff,

Thanks for reporting this!

If you don't provide a target path then `renku clone` uses the current directory. This worked for me:
```
$ mkdir /tmp/new-dir
$ renku clone git@dev.renku.ch:rokroskar/scratch-project
Cloning git@dev.renku.ch:rokroskar/scratch-project ...
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
Receiving objects: 100% (25/25), 6.21 KiB | 1.55 MiB/s, done.
Resolving deltas: 100% (8/8), done.                          
OK
```
My guess is that the directory you ran this command in it was not empty and that's why it failed. If you run `git clone git@renkulab.io:jeff.allen/testing.git .` you should see an error like that. Unfortunately, the underlying library that we use to interface with Git (GitPython) does not return the exact cause of the failure and we cannot print a better error message here.

One takeaway here is that it's better to use project's name as the target instead of the current directory when user does not provide a path. This is similar to what Git does. I'll create an issue for it.

**Comment by rokroskar** [comment]
@mohammad-sdsc ah I didn't realize that atm it unpacks the repo into the current directory? We should definitely follow the git convention here.

**Comment by mohammad-sdsc** [comment]
I've created an issue for that: https://github.com/SwissDataScienceCenter/renku-python/issues/856.
