### ISSUE TITLE
feat: service endpoint for project creation

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#862]
With #809 we can create projects from any template URL. We should then be able to offer a `/renku/projects.create` endpoint.

The payload would be:

```
{
  "project_name": "myproj",
  "template_url": https://template.url,
  "template_options": 
  {
    "option1": 1,
    "option2": 2
  }
}
```

The template options could be obtained from an endpoint like `/renku/projects.template.options?template_url=https://template.url`

**Comment by lorenzo-cavazzi** [comment]
I am a bit confused by `template_options`. Should they be the variables provided to feed the jinja interpreter? e.g., my template contains `{{ name }}`, and I will provide `{ "name": "Myname" }`?
I would rename that to `template_metadata` or `template_variables`. We are also missing the template name since a template repository may contain more than one, and we should allow the user to chose a tag/branch/commit

* /renku/projects.create
```
{
  "project_name": "myproj",
  "template_url": https://template.url,
  "template_ref": "master",
  "template_name": "Python basic",
  "template_variables": 
  {
    "var1": 1,
    "var2": "abc"
  }
}
```

Should we change the other endpoint name as well and make it a bit more `rpc` style?
* /renku/template.read_variables
```
{
  "template_url": https://template.url,
  "template_ref": "master",
  "template_name": "Python basic",
}
```

* /renku/template.read_manifest
We probably need another endpoint to read the manifest file to present the user with the available template names and descriptions. 
```
{
  "template_url": https://template.url,
  "template_ref": "master"
}
```
I am not sure about the url naming conventions, so the urls are just an example

**Comment by jsam** [comment]
I think we could tackle this topic this sprint. After I knockout all the DS issues I could address this. @lorenzo-cavazzi Is that okay with you?

**Comment by lorenzo-cavazzi** [comment]
If you want to do that firsthand it's ok, otherwise I can also do that in the current sprint :slightly_smiling_face:
