### ISSUE TITLE
feat: enable workflow graph extensions

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#867]
As a Renku user, I would like to add custom metadata to the `ProcessRun` node upon completion of a `renku run` execution. The process could be something like this:

1. The 3rd party library needs to be made aware of renku and produce the required metadata. It should store it in the `.renku/<extension-subdir>`
2. There should be a factory method of `ProcessRun` that instantiates the relevant subclass if the current commit contains metadata in the designated place
3. `renku log` will automatically include the metadata attached to the subclassed `ProcessRun` instance. 

addresses #594 
helps with #753 

Outstanding issues not considered here: how to extend the SHACL shapes checked by `renku log --strict` to include the third-party extensions.

**Comment by Panaetius** [comment]
After looking into how to enable plugins to interact with ProcessRun to record additional data related to e.g. Shogun or sklearn, some initial thoughts:

I don't like having to subclass ProcessRun/WorkflowRun. It makes it more difficult to reason about what happens if there's 2 or more plugins that both subclass it, plus it would put a lot of effort on developers of 3rd party libraries to understand the internals of renku-python.

After looking into it a bit, I think it makes more sense to annotate `ProcessRun` with arbitrary annotations provided by 3rd party libraries (or by us, if we need additional information).

My idea boils down to:
- ResearchObject (which wf4ever is a part of) already provides the mechanism of `Annotation`s, allowing arbitrary annotations for workflows etc. (https://wf4ever.github.io/ro-primer/ and https://code.google.com/archive/p/annotation-ontology/wikis/v2AnnotationCore.wiki `ao:annotates` )
- From the renku side, we don't have to care what's inside of an annotation, and we don't have to validate them via SHACL ourselves, instead plugins can provide simple SHACL shapes for the annotation:body graph nodes themselves.
- Adding annotations from plugins could be done in `CommandLineTool.create_run()`, with annotations just being a list of `@reverse:annotates` `Annotation` entries. That way multiple plugins can append to the list of annotations without interfering with each other
- CWL allows storing of arbitrary linked data metadata in cwl files, see https://www.commonwl.org/user_guide/17-metadata/index.html This makes it easy to store the annotations in the cwl files, and read them back when creating the graph, solving the issue of how to store them until we refactor the graph to not use *.cwl files.
- Annotations can be exported as-is on graph generation, without any interference needed on the part of the plugin, making it easier to implement plugins

So we only need a plugin hook that allows appending Annotations to `ProcessRun` (And in turn `WorkflowRun` since it's a subclass), and another hook allowing a plugin to supply SHACL shapes that the graph gets validated against (separately from our own validation). Plugins would have to make sure that the annotation bodies have some ontology type that the shape applies to and SHACL takes care of the rest.

Potential issues/open questions: 
- If two plugins use the same ontology for their annotations but with different SHACL constraints, or if a plugins uses a type that's already used by us but with different SHACL constraints, this could lead to validation errors. `Annotation` has a `context` property which might be (ab)used to to restrict plugin SHACL shapes to only apply to plugin annotations.
- We still need a way to declare what plugin created what annotation to make the plugin process traceable/reproducible, we might (ab)use `ao:context` for that as well. But it seems context in AO is intended for restricting parts of a resource an Annotation applies to, so I'm not sure if that'd be using it as intended. other candidates would be `ao:hasTopic`, `ao:author` or `ao:related`

**Comment by jsam** [comment]
I like the proposal and I agree with sub classing point which you mention. In theory I see no problems with the approach and I think it might work nicely. So I think we can proceed with the implementation of it! :muscle: 

Also, :+1: for the `pluggy` based implementation I really like how extending the graph becomes easy with it. I already see how we can utilize same architecture for other things (like implementing additional providers for import/export of datasets, etc).

IMHO, for open questions:
1) I think this is something we can work around by defining that mutually exclusive plugins can't be used (unless there is a actual use case I'm missing)
2) Since we need it to refer to which plugin created the annotation, `ao:context` might be the best pick.

Also, we discussed a few additional points - it would be great if you can paste to the proposal how the actual implementation of the plugin would look like (`setup.py` example).

**Comment by rokroskar** [comment]
Thanks for looking into this, the proposal sounds like a good direction! 

One detail that confuses me is that in the RO docs they refer to "annotation ontology" which seems like a dead google code project. I found this though, which looks much more recent: https://www.w3.org/TR/annotation-model/ - it involves some of the same people so it looks like the same thing. 

Assuming this is the same ontology, the examples they (RO) have also refer to the annotation body in a separate resource - this sounds tedious for our purposes IMO. 

I don't follow exactly how a plugin would inject the annotation - I guess an example/poc would help.

**Comment by Panaetius** [comment]
Wf4ever ended/was finalized in 2013, so from the point of view of that, the "annotation ontology" is not dead. It was just never migrated from google code to somewhere else when google code closed shop, so it's not active anymore.y All the V2 documentation is in their wiki, though ( https://code.google.com/archive/p/annotation-ontology/wikis ) and refers to the W3 annotation namespace:https://www.w3.org/2000/10/annotation-ns

In the wf4ever docs they just talk about body being a separate resource, but in the AO wiki ( https://code.google.com/archive/p/annotation-ontology/wikis/v2AnnotationBody.wiki ) it seems like it can be just another graph node.

Semantically/syntactically, they're both the same from what I can tell, so it just comes down to if we want to follow the wf4ever spec, or if that spec isn't as 4ever as the name implies and we want to got with a more current ontology. I'm fine with both, honestly, as since there seems to be a 1:1 mapping between the two, it'd be an easy switch from one to the other, so it doesn't matter too much for the initial POC which one is used :)

Making a plugin package for renku would require a `setup.py` in the package like this, along with an implementation of the hooks:
```
from setuptools import setup
setup(
    name="renku-shogun",
    install_requires="renku",
    entry_points={"renku": ["rensho = renku_shogun"]},
    py_modules=["renku_shogun"],
)
```

On the renku side, the plugin manager/host and plugin templates for `pluggy` can be in `renku/core/plugins.py` and that would be referenced by packages implementing a plugin, as well as the places in code that run plugin methods (It'd just contain the plugin host code and the plugin hook stub definitions).

`ProcessRun` gets a new list property `annotations` and a plugin gets passed some information as input (passing the `CommandLineTool` makes sense or at least the `kwargs` of `CommandLineTool.create_run`) and the hook is expected to output a list of `Annotation`s that get appended to the `ProcessRun.annotations` property. This way multiple plugins can add as many annotations side by side as they want without interfering with each other and without having to know about the internals of the code.

We should also add a small example plugin implementation, for document purposes and to have something to run tests on. This can be a separate packages or part of `renku-python`

The tasks that I see are (in order):
1. add pluggy to renku and ass the `plugins.py` file, basically scaffolding
2. add plugin functionality for ProcessRun/WorkflowRun annotations
3. add example plugin
4. help rensho to change their plugin to this
