### ISSUE TITLE
Dataset create raises `Dataset exists` for similar names

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#876]
There is a bug on dataset create command for datasets with long names and high similarity score.

Example:
```
renku dataset create "my super awesome dataset research project with super long name 1" 
```
results in
```
Use the name "my_super_awesome_dataset" to refer to this dataset.
OK

```

Now we create another one:
```
renku dataset create "my super awesome dataset research project with super long name 2"
```
results in
```
Error: Dataset exists: "my_super_awesome_dataset".
```

Expected behavior is that both of those datasets should be created.

**Comment by mohammad-sdsc** [comment]
We cannot avoid this fully because we create `short_name` from `name`. Even if we remove the length limitation we cannot do something meaningful regarding special character: the following two commands create the same `short_name` and the second one will fail:
```
renku dataset create 'some name'
renku dataset create `#some name#`
```

One solution will be to treat `name` as `short_name` (i.e. like before) in `renku dataset create` and pass a human-friendly name with `--name` or `--title`. @rokroskar what do you think?

**Comment by rokroskar** [comment]
@mohammad-sdsc yes this (I think) was sort of along the lines of what I was advocating for before at some point. It has the added benefit of solving the issue that @emmjab has brought up, which is that the user creates a dataset with some name but then the name they need to use to refer to that dataset is somehow different.
