### ISSUE TITLE
cli: renku run lfs policy should be configurable

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#919]
**Is your feature request related to a problem? Please describe.**

`renku run` puts everything except `.ipynb` files into lfs. This makes the files cumbersome to work with and cumbersome to display in the web UI.

**Describe the solution you'd like**

Improve default behavior and make use of lfs configurable. My proposal for the default behavior is:

* Files < 100kB do not go into git-lfs

I think this will greatly improve the renku experience. This behavior should be configurable. I think it will be enough to just make the cutoff file size configurable, but a further enhancement would be to allow the file type to play a role as well.

**Describe alternatives you've considered**

Manually remove files from LFS and rewrite history.

**Additional context**

**Comment by emmjab** [comment]
>renku run puts everything except .ipynb files into lfs. This makes the files cumbersome to work with and cumbersome to display in the web UI.

Can you be more specific about what was cumbersome for files in gitLFS?
e.g. Do you mean cumbersome to work with because you need to `git lfs pull` to work with the files in the interactive environment, and the web UI doesn't display a preview of the contents?

I agree we should include config for `renku dataset` and `renku run` to let users choose whether files are added to gitLFS, but I think arbitrary default behavior is confusing for users.

I think maybe the first run of a `renku dataset` or `renku run` command should print a message that lets users know the files are going to be added to gitLFS, and subsequent launching of notebooks will require running `git lfs pull` in some form to be able to interact with the data.

And maybe a UI change in the interactive environment launching page that more prominently announces whether there is content in LFS, and letting users configure pulling: https://github.com/SwissDataScienceCenter/renku-ui/issues/736

**Comment by ciyer** [comment]
You identify two ways in which LFS files are cumbersome to work with, but there are others. For example, diffing versions of files in LFS is not impossible, but complicated. 

As the name implies, LFS is designed for handling *large* files (see https://www.atlassian.com/git/tutorials/git-lfs).  The complexity it adds is justified for large files, but not for small files. The current default behavior of renku (putting everything except .ipynb files into git-lfs) is not what I think most users would do themselves.
