### ISSUE TITLE
Renku core service/renku-graph needs to be able to support different versions of renku

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#924]
With migrations, different repos can be in different states, so renku core service and renku graph need to be able to handle repos based on different versions of renku (side-by-side, e.g. with tox).

**Comment by rokroskar** [comment]
You mean to migrate the metadata on-the-fly if needed?

**Comment by Panaetius** [comment]
I mean depending on when a repository on gitlab was last used by a user, we can have repos in various states/versions of migrations. This has to be handled by the core service and graph service.

The core service might also raise an exception telling the user to upgrade, or it might use different versions of renku python depending on the repo that it needs to work on.

Similarly, the graph service has to auto-apply migrations when generating triples to always generate triples with the newest version of renku python (so all triples in the graph are consistent), or has to generate triples with a version of renku python matching the respective repository (in which case the graph could have differing triples depending on each projects migration state).

**Comment by ableuler** [comment]
I like the idea of keeping different renku-python versions side-by-side in the core service and choosing the right version for a given project. Like this we could avoid automatically migrating a users project.
I'm not sure we should do the same for renku graph though. I guess having a KG which contains metadata of different versions could be a nightmare. There I would vote for auto-applying migrations and always using the latest version of renku python.

**Comment by jachro** [comment]
I'd agree with Andreas. I imagine it could be pretty difficult, if not impossible, to build queries which deal with different flavours of e.g. dataset entities present in different projects. KG is a single bag for all the projects and I believe having a single representation of data for all the projects is the only way which could prevent us from not going mad.

What benefits do you see of using different versions of renku to generate triples?

**Comment by rokroskar** [comment]
Alternative is to insist that the user's repo is always at the version of the server? The core service could auto-migrate as much as possible. Then we don't have this weird state where the core service will be making commits with one version of renku but the user with a different version

**Comment by jsam** [comment]
@ableuler @jachro I completely agree with the points you are trying to achieve, however, I believe that supporting multiple versions of the core library in the service and juggling with them is not a solution that we want. This would split downstream into multiple versions which we have to maintain from the user's perspective, and this would simply lead to multiple problems and maintainability burden which I personally faced multiple times and would strongly advise against it.

I believe that a better solution might lay in the decoupling of concerns, both on the service level and on the level of the migration. First, the service level means that graph service should not shell out and generate triples via `renku log` command, but instead that concern should solely be on the service alone - #1442. With this in place, we only have to solve the problem now once and I believe we can do it by splitting the concerns on the migrations. 

Currently, our migrations are based on project level - meaning you need to migrate the whole project no matter if you want to execute read or write operations. This is in my humble opinion the heart of the issue here, and we could improve greatly here by splitting the concerns of read operations from write operations. For example: 

1) Core library should be able to generate the graph no matter of version of the metadata - this has to be true for all read operations all the time (especially for graph building - `/log` endpoint)
    - We could think about this as executing migrations on the fly (and only migrations related to metadata change so they should be executed fast-ish)
    - We do not persist those and on any read operation we don't raise migration required exception

2) Core library should not support write operations if the metadata state is not persisted on the latest version possible. This has multiple benefits: 
    - Prevent fragmenting our user issues into multiple streams where each version is cherry-picked and makes troubleshooting a nightmare
    - Keeps us away from backporting features nightmare  which can easily happen once we are on that avenue
    - Keeps us on a path where moving forward is easy to reason about and move forward in a clean way
    - Migrating people to use new version should be enforced in some way to due to a healthy product adoption cycle (we don't want to get stuck where the majority of our user base will use super old versions)

From my pov (2) is a good thing both from product management and developers perspective we should think about before we rush into fragmenting and supporting multiple versions. With that said, I believe splitting of our concerns should not stop there - splitting migrations on read from write operations is just a first step. I believe we need this level of control per command level and I've described some of those ideas in #1437.

**Comment by Panaetius** [comment]
Current porcelain on the service supports this to some extent.
